version: "3"

volumes:
  db-backups:
  geoserver_data:
  geodb-data:
  users_api_data:
  geofiles_data:
  users_layers_data:

services:
  fluentd:
    image: nessgis/logs-service
    links:
      - "elasticsearch"
    ports:
      - "24224:24224"
      - "24224:24224/udp"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.2
    environment:
      - "discovery.type=single-node"
    expose:
      - "9200"
    ports:
      - "9200:9200"

  kibana:
    image: kibana:7.10.1
    links:
      - "elasticsearch"
    ports:
      - "5601:5601"
  db:
    image: kartoza/postgis
    volumes:
      - ./resources/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - geodb-data:/var/lib/postgresql
    ports:
      - "5431:5432"
    environment:
      - POSTGRES_DB=gis,gwc
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=manti2468
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: on-failure

  mock_config_server:
    container_name: mock_config_server
    volumes:
      - ./gis_mock_server/app/:/usr/src/app/
    build: ./gis_mock_server
    ports:
      - "8020:80"

  users_api:
    depends_on:
      - fluentd
    container_name: users-api
    image: nessgis/users-api
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    ports:
      - 8030:8000
    environment:
      - DATABASE_URL=postgresql://postgres:secret@users_api_db/gis_users
      - API_KEY=iwhdiodhoiwehwioh
      - API_KEY_NAME=apiKey
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: users_api
  users_api_db:
    image: postgres:12.1-alpine
    volumes:
      - users_api_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=gis_users
    ports:
      - 5432:5432
  auth_api:
    depends_on:
      - fluentd
    image: nessgis/auth-api
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    environment:
      - CREDENTIALS_URL=http://users_api:8000/users/credentials
      - CREDENTIALS_API_KEY=iwhdiodhoiwehwioh
      - SECRET_JWT_KEY=71e44ea7cc314cf222fcee8403743c5b4056ebc1c9d82b0c95c0c5fc17de89c1
      - TOKEN_EXPIRATION_MINUTES=30
      - ACCESS_TOKEN_KEY=token
    ports:
      - 8040:8000
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: auth_api
  geofiles_api:
    depends_on:
      - fluentd
    container_name: geofiles_api
    image: nessgis/geofiles-api
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./geofiles-api/src:/usr/src/app/
    environment:
      - DATABASE_URL=postgresql://postgres:secret@geofiles_db/uploads
      - CREDENTIALS_URL=http://auth_api:8000/auth/credentials
      - ACCESS_TOKEN_KEY=token
      - FILE_EOL=10
    ports:
      - 8050:8000
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: geofiles_api
  geofiles_db:
    image: postgres:12.1-alpine
    volumes:
      - geofiles_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=uploads
    ports:
      - 5438:5432
  users_layers_api:
    depends_on:
      - fluentd
    container_name: users_layers_api
    build: ./users-layers-api/src
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./users-layers-api/src:/usr/src/app/
    environment:
      - DATABASE_URL=postgresql://postgres:secret@users_layers_db/custom_layers
      - CREDENTIALS_URL=http://auth_api:8000/auth/credentials
      - ACCESS_TOKEN_KEY=token
      - FILE_EOL=10
    ports:
      - 8060:8000
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
